// calcul/src/components/Calculator.vue
<template>
  <div class="container">

  <div class="number">
    <button @click="append('0')">0</button>
    <button @click="append('1')">1</button>
    <button @click="append('2')">2</button>
    <button @click="append('3')">3</button>
    <button @click="append('4')">4</button>
    <button @click="append('5')">5</button>
    <button @click="append('6')">6</button>
    <button @click="append('7')">7</button>
    <button @click="append('8')">8</button>
    <button @click="append('9')">9</button>
  </div>

    <div class="operator">
    <button @click="add" >+</button>
    <button @click="substract" >-</button>
    <button @click="multiply" >x</button>
    <button @click="divide" >/</button>
    <button @click="equal" >=</button>
    <button @click="clear">C</button>
    </div>

    <div class="total">
    {{total || '0'}}
    </div>
  </div>
</template>


<script>
export default {
    data() {
        return {
            previous: null,
            total: '',
            operator: null,
            operatorClicked: false,
        }
    },
    methods: {
        clear() {
          this.total = '';
        },

        append(number) {
          if (this.operatorClicked) {
          this.total = '';
          this.operatorClicked = false;
          }
          this.total = `${this.total}${number}`;
        },

         setPrevious() {
          this.previous = this.total;
          this.operatorClicked = true;
        },

        add() {
          this.operator = (a, b) => a + b;
          this.setPrevious();
        },

        substract() {
          this.operator = (a, b) => b - a;
          this.setPrevious();
        },

        multiply() {
          this.operator = (a, b) => a * b;
          this.setPrevious();
        },

        divide() {
          this.operator = (a, b) => b / a;
          this.setPrevious();
        },

        equal() {
          this.total = `${this.operator(
          parseFloat(this.total),
          parseFloat(this.previous)
          )}`;
          this.previous = null;
        }
    }
}
</script>

<style scoped>
.total {
background-color: cornflowerblue;
height: 150px;
}

button {
 width: 150px;
 height: 150px;
}

h3 {
  font-size: 1.2rem;
}

.greetings h1,
.greetings h3 {
  text-align: center;
}

@media (min-width: 1024px) {
  .greetings h1,
  .greetings h3 {
    text-align: left;
  }
}
</style>

// calculator-angular/src/app/calculator/calculator.component.ts
import { Component} from '@angular/core';

@Component({
  selector: 'calculator',
  templateUrl: './calculator.component.html',
  styleUrls: ['./calculator.component.css']
})
export class CalculatorComponent {
  public total: number = 0;
  public current: number = 0;
  private previous: number = 0;
  private operator: string = '';
  private operatorClicked: boolean = false;

  getValue(number: number) {
    if(this.operatorClicked) {
      this.total = 0;
      this.operatorClicked = false;
    }

    this.total = parseInt(`${this.total}${number}`);
  }

  add() {
    this.total = this.total + this.previous;
    this.setPrevious();
    this.setOperator('+');
  }

  substract() {
    this.total = this.total - this.previous;
    this.setPrevious();
    this.setOperator('-');
  }

  divide() {
    if(this.previous != 0) {
      this.total = this.previous / this.total;
    }
    this.setPrevious();
    this.setOperator('/');
  }

  multiplicate() {
    if(this.previous != 0) {
      this.total = this.previous * this.total;
    }
    this.setPrevious();
    this.setOperator('*');
  }

  percent() {
      this.total = this.total / 100;
      this.setPrevious();
  }

  setPrevious() {
    this.previous = this.total;
    this.operatorClicked = true;
  }

  setOperator(operator: string) {
    this.operator = operator;
  }

  equal() {
    console.log(this.previous)
    console.log(this.current)
    console.log(this.operator)

    switch (this.operator) {
      case '+':
        this.total = this.total + this.previous ;
        break;

      case '-':
        this.total = this.previous - this.total ;
        break;

      case '/':
        this.total = this.previous / this.total ;
        break;

      case '*':
        this.total = this.total * this.previous ;
        break;
    }

    this.previous = 0;
  }

  clear() {
    this.total = 0;
    this.previous = 0;
  }
}

<style>
body {
  display: flex;
  justify-content: center;
  flex-wrap: wrap;
  font-size: 55px;
}
button {
  width: 150px;
  height: 150px;
  font-size: 45px;
}

.total {
  background-color: lightblue;
  height: 150px;
  font-size: 65px;
}

.container {
  margin-top: 40px;
  width: 600px;
}
</style>

<div class="container">

    <div class="total">{{ total }}</div>

  <div class="top-buttons">
    <button (click)="clear()">C</button>
    <button (click)="percent()">%</button>
  </div>

  <div class="operators">
    <button (click)="add()">+</button>
    <button (click)="substract()">-</button>
    <button (click)="divide()">/</button>
    <button (click)="multiplicate()">*</button>
  </div>

  <div class="numbers">
    <button (click)="getValue(9)">9</button>
    <button (click)="getValue(8)">8</button>
    <button (click)="getValue(7)">7</button>
    <button (click)="getValue(6)">6</button>
    <button (click)="getValue(5)">5</button>
    <button (click)="getValue(4)">4</button>
    <button (click)="getValue(3)">3</button>
    <button (click)="getValue(2)">2</button>
    <button (click)="getValue(1)">1</button>
    <button (click)="getValue(0)">0</button>
    <button (click)="equal()">=</button>
  </div>

</div>
